baseurl = "http://alxpy.com/"
languageCode = "ru"
title = "alxpy.com"
theme = "hugo-cactus-theme"

publishdir = "../."

[params]
    name = "Alex Kuzmenko"
    twitter = "_alxpy"
    enableRSS = true
    disqusShortname = "alxpycom"
